runtime: go
api_version: go1.8

handlers:
- url: /poll
  script: _go_app
  secure: always
  login: admin

- url: /update-stats
  script: _go_app
  secure: always
  login: admin

- url: /(.*)
  script: _go_app
  secure: always
