application: blockvote-153813
module: default
version: v1
runtime: go
api_version: go1

handlers:
- url: /poll
  script: _go_app
  secure: always
  login: admin

- url: /stats
  script: _go_app
  secure: always
  login: admin

- url: /(.*)
  script: _go_app
  secure: always
